### ISSUE TITLE
Slow performance when generating spec with external dependencies

### ISSUE THREAD

**Issue by matrixik** [swaggo/swag#1032]
**Describe the bug**
When using external dependencies `swag` is becoming really slow when generating swagger specification files.
I created example repository with simple code: https://github.com/matrixik/swag-perf
On my computer with CPU Intel Core i7-4790 it's taking around 30 seconds to generate specification files. This is simple example on stationary computer. We have some internal projects that on laptops take over 10 minutes to generate spec files.

At the same time same code will generate swagger spec files using https://github.com/go-swagger/go-swagger in around 3 seconds. 
We changed some smaller internal projects to `go-swagger` and it's still generate everything in under 5 seconds when `swag` need over 1 minute and 30 seconds to output spec files on my computer. Output from both is almost the same but `swag` is minimum 10 times slower.
We would like to stay with `swag` because it's annotations are more readable but long generation times are getting in the way.

**To Reproduce**

*Clone example repository*
`git clone https://github.com/matrixik/swag-perf.git`

*Clone and fix swag*

`git clone https://github.com/swaggo/swag.git && cd swag`

`git checkout v1.7.3`

`git apply ../swag-perf/swag_annotation_error.patch` - needed to avoid exiting on wrong annotations in dependencies (or you can use v1.6.7 without patching)
```diff
diff --git i/parser.go w/parser.go
index aaa8112..fc6801e 100644
--- i/parser.go
+++ w/parser.go
@@ -636,7 +636,8 @@ func (parser *Parser) ParseRouterAPIInfo(fileName string, astFile *ast.File) err
 			for _, comment := range astDeclaration.Doc.List {
 				err := operation.ParseComment(comment.Text, astFile)
 				if err != nil {
-					return fmt.Errorf("ParseComment error in file %s :%+v", fileName, err)
+					fmt.Println("Error found in file:", fileName, "error:", err)
+					// return fmt.Errorf("ParseComment error in file %s :%+v", fileName, err)
 				}
 			}
 ```

`go build -o swag_fix ./cmd/swag`

*Build swagger spec*

`cd ../swag-perf`

Generate Swagger spec file:

With https://github.com/swaggo/swag

* v1.7.3:
  `time ../swag/swag_fix init -o swagger/docs --md swagger/markdown --parseDependency true`
* v1.6.7:
    `time swag init -o swagger/docs --md swagger/markdown`

With https://github.com/go-swagger/go-swagger

`time swagger generate spec -o ./swagger-ui/swagger.json --scan-models`

Start app:

`go run main.go`

Open swagger:

For swag output: http://localhost:8080/swagger/index.html

For go-swagger output: http://localhost:8080/swagger-ui/

**Expected behavior**
Swagger spec files would be generated in short time (like under 10 seconds, similar to `go-swagger` time).

**Your swag version**
v1.7.3

**Your go version**
go1.17.2 linux/amd64

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS x86_64

**Additional context**
`--parseDepth 1` is not helping.

**Comment by sunlintong** [comment]
Any update? same problem.

**Comment by ubogdan** [comment]
@sunlintong please feel free to contribute.

**Comment by pytimer** [comment]
I also have the same question when use `swag` generate the swagger docs in my project, it wait 7 minutes.
I read the swag code that it use [depth](https://github.com/KyleBanks/depth) to get all go dependencies and loop the deps too many times.

`depth` use go standard library `build.Import` default and it will call the `build.Import` too many times, it will spent too many times when the large dependencies,
so i directly use `go list` command instead of `build.Import`, it only call once. Recompile swag and run `./swag init -g main.go -o swaggerdocs --parseInternal --parseVendor --parseDependency` only have 1 minute.

I want to add this code in the `depth` project, but have not found a proper way to add it. And if use `depth`, `swag` still need to loop too many times in [the line](https://github.com/swaggo/swag/blob/97ea98ec1bd528b87a0fd6f5e3493a052dc762c0/parser.go#L296), so i refactor the `swag` get ast files code.

The code demo link: [Imporve performance when generating spec with external dependencies](https://github.com/pytimer/swag/commit/5840ead4de34369f2ee78b4329ed78a38f1846bd)

If it can help anyone, i would great to send pr.

**Comment by pytimer** [comment]
Send a pr that added the `--parseGoList` flag, the default value is true default, `swag` use go list for dependency parser. If it's set to false, `swag` still use depth for dependency parser.
