### ISSUE TITLE
How to override param some common field in struct in specific router?

### ISSUE THREAD

**Issue by morefreeze** [swaggo/swag#1097]
```go
// @Param op1req body Op1Req true "in this operation, operator is required"
// @Param op1req.operator body string true "this operator is required"
func HandleOp1(c *gin.Context) {
}

// @Param op2req body Op2Req true "in this operation, operator is NOT required"
func HandleOp2(c *gin.Context) {
}

type Common struct {
  Operator string `json:"operator"`  // can't add tag `validate:"required"`, that will affect op2req
}

type Op1Req struct {
  Common
  Name string
}

type Op2Req struct {
  Common
  Other string
}

```
I want to set common param `operator` as required in Op1Req, but I don't want to set it required in Op2Req, so I wonder is there some way define @Param to override some field in struct.

**Describe the solution you'd like**
Some way could override attribute of some field of struct.

**Comment by sdghchj** [comment]
Not support.
It may be a better solution to redesign your structs

**Comment by Kowiste** [comment]
This could be a good implementation, maybe define multiple .swaggo files to override the parse and put it like:

`// @Param default body model.Notification true "Request body" swaggo1`

or inside .swaggo file define tags and later use it in the params like:

`// @Param default body model.Notification true "Request body" tag1`

**Comment by morefreeze** [comment]
I didn't get. Your example can't show which override which.

> This could be a good implementation, maybe define multiple .swaggo files to override the parse and put it like:
> 
> `// @Param default body model.Notification true "Request body" swaggo1`
> 
> or inside .swaggo file define tags and later use it in the params like:
> 
> `// @Param default body model.Notification true "Request body" tag1`

**Comment by Kowiste** [comment]
Ok I'm going to extend a bit more, if in the .swaggo, using the example, it would be nice to implement something like:

`
#tag1
// Replace all NullInt64 with int
replace database/sql.NullInt64 int

// Don't include any fields of type database/sql.NullString in the swagger docs
skip    database/sql.NullString

#tag2 
// Don't include any fields of type database/sql.NullString in the swagger docs
skip    database/sql.NullString
`
later in definition of the parameter it could be call like

`// @Param testing body model.Notification true "Request body" tag1`

so for the param testing  is using the replace and skip and we can have other param with the same struct that use tag2 and skip only. 

`// @Param other body model.Notification true "Request body" tag2`

Maybe instead of #tag it will be better like a json or other kind of structure but something like that.

**Comment by ubogdan** [comment]
@Kowiste it's not nice at all . 

You should use [DTO](https://en.wikipedia.org/wiki/Data_transfer_object) for this if the object you are using for request/response is not under your control to change.
