### ISSUE TITLE
flag provided but not defined: -parseFuncBody

### ISSUE THREAD

**Issue by yarex007** [swaggo/swag#1884]
**Describe the bug**
swag init --parseFuncBody gives error  flag provided but not defined: -parseFuncBody

**To Reproduce**
execute swag init --parseFuncBody

**Expected behavior**
Should execute according to help

**Your swag version**
1.16.3

**Your go version**
1.23.0

**Desktop (please complete the following information):**
win 11

**Comment by bsnuggs1** [comment]
@yarex007 It seems like this logic was [merged in June](https://github.com/swaggo/swag/pull/1824), but the last release was back in Feb.  Likely this will become available in the next version.    

You could potentially grab the changes by forcing an install from master, but you may encounter other problems since it has not been released yet,

```go install github.com/swaggo/swag/cmd/swag@master```
