### ISSUE TITLE
Hard-code schema definitions?

### ISSUE THREAD

**Issue by abdulito** [swaggo/swag#207]
Hi,

We have models that are complicated and have things that are not supported yet such as maps. 

```
panic: ParseDefinitions not supported 'Map' yet.

goroutine 1 [running]:
```

Is there a way that i can hard-code the data mode schema in the comments?

Also, is there a way to inline schemas without having with them references to schema definitions?

Thanks

**Comment by pei0804** [comment]
I thought of this plan once, but it seemed that there was not much demand, so I stopped.
Do you want?

**Comment by Ashtonian** [comment]
came here for this too, I have a  field 
```
Metadata     types.JSONBMap `json:"metadata,omitempty" binding:"" example:""`
```
that is `type JSONBMap map[string]interface{}` under the hood, used for interacting with postgres jsonb types.

Current Behavior:
panics with `panic: ParseDefinitions not supported 'Map' yet.`

Desired Behavior: 
silent warning instead of panic, stating it will be an empty string like elsewhere I think. Eventually map support, or a way to specify the shecma def inline if possible. 

Again thanks for all your work

**Comment by pei0804** [comment]
At the initial stage, we implemented implementation with panic.
Can you fix it?

**Comment by abdulito** [comment]
Thanks for the fix. Can we at least have it parse maps as objects instead of strings?

**Comment by sdghchj** [comment]
fixed
