### ISSUE TITLE
Conflicting package + struct name

### ISSUE THREAD

**Issue by rubensayshi** [swaggo/swag#225]
**Describe the bug**
When there's 2 models (used in `@success` tags) only 1 can be used and the result is funky 

I've created a test scenario that demonstrates the problem 100x better than I can do in text, but the gist of it;

there's `package1` and there's `package2`, both contain api methods in their `api.go` file and both contain a `data` subpackage with a `Foo` struct.  
because swag only uses the top level package name everywhere these 2 `Foo` structs will conflict because they're both considered to be `data.Foo`.

as a result the api methods in both `package1` and `package2` will have the same `data.Foo` even though they should be different.  

to add a little extra funkiness, because the order on go's map is random, the resulting generated spec switches around between the 2 every time you generate it.

**To Reproduce**
see the test case: https://github.com/rubensayshi/swag/tree/conflicting-model-name-test-case/testdata/conflicting_model_name

**Your swag version**
master

**Comment by cdyue** [comment]
same issue

**Comment by alexanderbez** [comment]
The issue is pretty persistent for a project I'm working on where we use a type, `Params` in many packages which causes conflicts like described in the issue. Any updates on a solution?

**Comment by uhhc** [comment]
same issue on 1.6.3

**Comment by wsnotify** [comment]
I wanted to create a new issue, but the github suggested this one, here is the full description:

**Describe the bug**
If code uses two packages that contains types with same name, swag genarate wrong json/yaml.

**To Reproduce**
I created a [test code](https://github.com/wsnotify/swag-test) to demonstrate this error.
Just run `swag init` inside. This may require several attempts, depending on the computer (10 to 20 on my).

**Expected behavior**
```json
    "definitions": {
        "bar.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                }
            }
        },
        "foo.Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                }
            }
        }
    }
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Your swag version**
v1.6.5

**Your go version**
go1.13.7 linux/amd64

**Desktop (please complete the following information):**
 - OS: KDE neon (linux, ubuntu)

**Additional context**
In test runs  `code.type` may be both `integer` or both `string`.

I encountered this problem when I used in my code two dependencies in which there were `ErrorCode` in such configurations as in the example.


---

I traced this problem to `property.go:92` that sends to `parser.go:519` (rewrite in `parser.CustomPrimitiveTypes` map).

**Comment by rubensayshi** [comment]
@wsnotify that's indeed the same issue as this one, unfortunately I never got around to fixing it ... it's been on my todo since forever ... :(

**Comment by wsnotify** [comment]
@rubensayshi please check #629
