### ISSUE TITLE
Update the Swagger UI

### ISSUE THREAD

**Issue by 0zAND1z** [swaggo/swag#292]
Hi team,

**CONTEXT:** This is one of those feature requests that focuses on the small things that makes Swagger perfect tool for documenting APIs..

**PROPOSAL:** As we know, https://petstore.swagger.io/ now has an updated Swagger UI. Can we migrate our current UI screen from this
<img width="512" alt="image" src="https://user-images.githubusercontent.com/11145839/51883860-d7983600-23aa-11e9-9086-b0b6216ec1db.png">

 to that 

<img width="512" alt="image" src="https://user-images.githubusercontent.com/11145839/51883871-e4b52500-23aa-11e9-96c8-2531837f7fe8.png">

?

Would also love to know if I can contribute for the same.. Just need some directions on changing the Swagger UI boilerplate code..

Looking forward to your response. Cheers!

**Comment by pei0804** [comment]
Yes. You can change to new UI.
eg: https://github.com/swaggo/gin-swagger

If you have motivation. Welcome to PR.
If I have my time. I change to new UI.

**Comment by Nerzal** [comment]
I just cannot find the referenced css file, which is used in order to update it.
@pei0804 can you give a hint?

**Comment by easonlin404** [comment]
@Nerzal we used embedded files that generated by [fileb0x](https://github.com/UnnoTed/fileb0x), and there are some projects like [gin-swagger](https://github.com/swaggo/gin-swagger) imported  embedded files in their project base:
```go
import "github.com/swaggo/gin-swagger/swaggerFiles" // swagger embed files

```
some imported by [swaggo/files](https://github.com/swaggo/files) repo like:
https://github.com/swaggo/http-swagger/blob/79126c07518e87da94d8fff0c33c5e185746f51d/swagger.go#L10

so you can update this embedded files  by using [fileb0x](https://github.com/UnnoTed/fileb0x). Besides, also can add new method that can specify swagger files directory path since some [issues](https://github.com/swaggo/files/issues).
