### ISSUE TITLE
Could swag support registration twice?

### ISSUE THREAD

**Issue by superwy** [swaggo/swag#385]
panic: Register called twice for swag: swagger
![image](https://user-images.githubusercontent.com/29361969/56899006-f5b62500-6ac4-11e9-8ec5-2d676f111772.png)

**Comment by easonlin404** [comment]
what is your scenario? can you tell why you want to register twice?

**Comment by superwy** [comment]
There are multiple modules in the project, each module can have independent documentation

**Comment by easonlin404** [comment]
And you want to expose only one swagger endpoint?

**Comment by superwy** [comment]
For example: I want to visit "http://localhost/admin/doc " to get the documentation of the management module, visit "http://localhost/home/doc" to get the documentation of the client module.

**Comment by easonlin404** [comment]
In your scenario, I think it's work for to visit two documentation in difference endpoint. Would you post your code on it to reproduce?

**Comment by superwy** [comment]
您好， 請多等幾天

**Comment by mziia** [comment]
Any thoughts? Solved this problem?

**Comment by easonlin404** [comment]
@superwy ping

**Comment by ubogdan** [comment]
@easonlin404 
We have a singleton here
https://github.com/swaggo/swag/blob/c19280e76fac72a09e9730a4b3c9ae3e144d9b3a/swagger.go#L22-L33

Somewhere in the code he is including both swagger docs in order to add them to different router.
```
import (
	_ "github/[project_path]/web/admin/docs"
	_ "github/[project_path]/web/user/docs"
)
```
Actually it really doesn't matter his code as soon as the generated docs does the following: 
https://github.com/swaggo/swag/blob/c19280e76fac72a09e9730a4b3c9ae3e144d9b3a/example/basic/docs/docs.go#L299-L301

**Comment by ubogdan** [comment]
@superwy since your use case is something special, you should find an alternative way to do this .
by example you can create 2 routes that will static serve your module/admin/docs/swagger.json and module/user/docs/swagger.json so your code won't panic any more.
