### ISSUE TITLE
swaggerignore:"true" not work

### ISSUE THREAD

**Issue by im-zhangxi** [swaggo/swag#652]
**Describe the bug**
 add swaggerignore true to sruct field, not work

**To Reproduce**
my code
```
type Shop struct {
	app.Entity `bson:",inline"`
    // this is name
	Name string `bson:"name" json:"name,omitempty" swaggerignore:"true" form:"name" validate:"required,min=6,max=20"`
	// this is mobile
	Mobile  string `bson:"mobile" json:"mobile,omitempty" form:"mobile" validate:"required,min=6"`
}
```
swag init 

**Expected behavior**
I expect the name not to show
**Screenshots**
![image](https://user-images.githubusercontent.com/18593080/77752600-d45a1200-7062-11ea-8354-4ddd87db9858.png)

**Your swag version**
swag version v1.6.5 and master

**Your go version**
go version go1.14 windows/amd64

**Additional context**
https://github.com/swaggo/swag/issues/632

Hope to help me

**Comment by sdghchj** [comment]
Master is ok. 
You can pull and debug it.

**Comment by Hades300** [comment]
I came across the same problem.When I struggle with the latest release I found #632 ,Then I tried
`go get -u github.com/swaggo/swag@latest` But the issue was still threre .
![6D9566F2-99D6-47F5-A956-4D44ED313836](https://user-images.githubusercontent.com/43801247/77813497-5566d880-7066-11ea-9409-91b7736247db.png)
using eample in the README
![Snipaste_2020-03-27_19-55-39](https://user-images.githubusercontent.com/43801247/77813519-7e876900-7066-11ea-8656-47d694974b9d.png)
annotation for a handler
![2DF94914-9071-4C14-90B5-D4DAEF1F26C0](https://user-images.githubusercontent.com/43801247/77813529-952dc000-7066-11ea-8cb0-b8f08e4c6c60.png)
And the output
![D5E8E74E-6B82-4BBE-AA3A-4F89AB466BFB](https://user-images.githubusercontent.com/43801247/77813538-ab3b8080-7066-11ea-8f09-d81989655f3a.png)
go version go1.13.3 darwin/amd64 here

**Comment by sdghchj** [comment]
@Hades300 I think you have to read [usage](https://github.com/swaggo/swag#getting-started)  in README.md.
Use the pre-built binary to run "swag init" to reproduce docs.

**Comment by Hades300** [comment]
@sdghchj Works perfectly , thank you 🐳

**Comment by im-zhangxi** [comment]
@sdghchj   When will it be release?

**Comment by sdghchj** [comment]
@im-zhangxi  Wait until #651 fixed.

**Comment by im-zhangxi** [comment]
Looking forward to it. Thank you.
