### ISSUE TITLE
err when parse api.md if got err as below when got double quotation mark in api.md

### ISSUE THREAD

**Issue by wkj89** [swaggo/swag#738]
err as below when got double quotation mark in api.md
`Errors
Hide
Parser error on line 5
missed comma between flow collection entries`

api.md file looks like:
`
"a"
`

I guess:

var SwaggerInfo = swaggerInfo{
	Version:     "0.1",
	Host:        "",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Cmdb Api",
	Description: "something",
}

I think should chnage     Description: "something"  to   Description: `something`
user `` instead of "" or  escape  ”“

**Comment by sdghchj** [comment]
More detailed, please.

**Comment by wkj89** [comment]
> More detailed, please.

well，I got an api.md file for the main function with description.markdown comment

And in api.md file only have :    "a"

then  swag init

run main.go   and   open http://127.0.0.1:8080/swagger/index.html

i got err:

```
Errors 
Hide Parser error on line 5 
missed comma between flow collection entries

```

**Comment by sdghchj** [comment]
Got it, It's a bug of swagger ui. I think.

**Comment by j0s** [comment]
This problem can also be reproduced without any markdown involved. Just type any string with quotation marks in the general API `@Description` field.
I actually this is a bug stemming from the two step application of templates in  [`writeGoDoc()`](https://github.com/swaggo/swag/blob/940d07268e91254eb18c2978cda233381ab643cb/gen/gen.go#L160) and then in [`ReadDoc()`](https://github.com/swaggo/swag/blob/940d07268e91254eb18c2978cda233381ab643cb/gen/gen.go#L283), resulting in the escaping of quotes disappearing. Since the problem only appears when running the generated doc.go, it doesn't show up in `swagger.{json,yaml}`. I came up with a workaround that seems to work well enough: https://github.com/swaggo/swag/pull/743

**Comment by wkj89** [comment]
> This problem can also be reproduced without any markdown involved. Just type any string with quotation marks in the general API `@Description` field.
> I think this is a bug stemming from the two step application of templates in [`writeGoDoc()`](https://github.com/swaggo/swag/blob/940d07268e91254eb18c2978cda233381ab643cb/gen/gen.go#L160) and then in [`ReadDoc()`](https://github.com/swaggo/swag/blob/940d07268e91254eb18c2978cda233381ab643cb/gen/gen.go#L283), resulting in the escaping of quotes disappearing. Since the problem only appears when running the generated doc.go, it doesn't show up in `swagger.{json,yaml}`. I came up with a workaround that seems to work well enough: #743

GOD JOB！

**Comment by Dysar** [comment]
Hi guys, any working example or do we have to wait for PR still?

**Comment by BillZong** [comment]
Use quote in doc `Description` trigger the error, simply change it to single quote would solved this problem.
Add some document for this issue would be nice for impatient users.
