### ISSUE TITLE
Add @Security to route group or middleware

### ISSUE THREAD

**Issue by nnanto** [swaggo/swag#777]
I've a route group that uses a route middleware to authorize users. It'd be easier to add @Security tag to the group or to the middleware somehow, rather than to each route specified in the group. 

Something like this.

```
@Security ApiKey
privateGroup := srv.Group("/private")
```

Framework : gin

**Comment by ubogdan** [comment]
@nnanto 
I'm afraid it's not possible at the moment since swag doesn't parse annotations/comments in the function body and doesn't analyze in any way the definition of the function or variable the annotation text was written.

Such an Implementation may require swag to analyze your go code flow, assemble it, and apply this kind of general tag you are speaking about. This will introduce more code complexity, computational time, and memory usage.
