### ISSUE TITLE
Multiple methods definition

### ISSUE THREAD

**Issue by thomaspoignant** [swaggo/swag#797]
**Is your feature request related to a problem? Please describe.**
I use `go-chi` and I have an endpoint which can handle all http method.
I want to describe it to see it in swagger.
ex:
```go
r.HandleFunc("/*", controller.RewriteURL(shadowCompareHandler, rewriteRule))
```
**Describe the solution you'd like**
I would like to be able to configure the router option with all the method it supports.

```go
// @Router / [get, post, put, options]
```

**Describe alternatives you've considered**
I have considered creating a fake handler for each method but it becomes verbose and doesn't bring value.

**Comment by ubogdan** [comment]
The option to describe a single route with many options does not get any real benefit if you are really building a RESTfull sevice.
in most cases, the routes need additional parameters that you will want to be defined per method. (which is not possible) . 
In the end, you will require an expert to define the annotations in order to get the right definitions. 

As a work-around you can copy the same definition on top of additional 3 empty handlers and you will get the same result.

**Comment by thomaspoignant** [comment]
My use case is that I created a proxy endpoint that can shadow traffic, in that case, it should manage every method.

I can use 3 empty handlers but it will add some code that does nothing and it will be hard to understand for future contributors.

**Comment by ubogdan** [comment]
@thomaspoignant I perfectly understand your case but the documentation won't reflect the true get/post/put request/response pair.
