### ISSUE TITLE
can not parse response comment

### ISSUE THREAD

**Issue by thejdavid** [swaggo/swag#803]
Hello,

Trying to use annotations i get the  " can not parse response comment "  for those comments 👍 

```
// @Success http.StatusOK {string} "OK"
// @Failure http.StatusBadRequest {string} "Bad Request"
// @Failure http.StatusUnauthorized {string} "Unauthorized"
// @Failure http.StatusInternalServerError {string} "Internal Error"
```
Not sure why. Tried many different combination 

the doc says 

// @Success 200 {string} string	"ok"

**Comment by sarathsp06** [comment]
The following regex is used to parse the comment and it expects `200` instead of `http.StatusOK`. You should explicitly mention the http status code instead of using the `http.StatusOk` constant from go-stdlib

`([\d]+)[\s]+([\w\{\}]+)[\s]+([\w\-\.\/\{\}=,\[\]]+)[^"]*(.*)?`

[regex101](https://regex101.com/r/CXdVBP/1)

**Comment by thejdavid** [comment]
yep that was the issue the parser cannot read the content a constant
